import { MessageSquare } from 'lucide-react'

import type { PurchasePreviewValues } from '../purchases/PurchaseForm'
import { formatCurrency } from '../../utils/format'

interface MessagePreviewProps {
  values: PurchasePreviewValues | null
}

function buildMessage(values: PurchasePreviewValues): string {
  const name = values.customerName || 'customer'
  const product = values.product || 'item'
  const amount = values.amount ? formatCurrency(values.amount) : 'GHS 0.00'
  const shop = values.shopName || 'your shop'
  return `Hi ${name}, thank you for purchasing ${product} for ${amount} at ${shop}. We appreciate your business.`
}

export default function MessagePreview({ values }: MessagePreviewProps) {
  const hasData = Boolean(values && (values.customerName || values.product || values.amount))
  const message = hasData && values ? buildMessage(values) : null

  return (
    <section className="flex flex-col rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="flex items-center gap-2 border-b border-slate-200 px-5 py-4">
        <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-50 text-brand-600">
          <MessageSquare className="h-4 w-4" aria-hidden="true" />
        </span>
        <div>
          <h2 className="text-base font-semibold text-slate-900">Message Preview</h2>
          <p className="text-xs text-slate-500">SMS the customer will receive</p>
        </div>
      </div>

      <div className="flex flex-1 items-center justify-center p-5">
        <div className="w-full max-w-xs">
          <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
            <div className="flex items-center gap-2 border-b border-slate-100 bg-slate-50 px-4 py-3">
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-brand-600 text-xs font-bold text-white">
                GAE
              </div>
              <div className="min-w-0">
                <p className="truncate text-xs font-semibold text-slate-900">
                  Great Alexender Enterprise
                </p>
                <p className="text-[10px] text-slate-400">SMS</p>
              </div>
            </div>
            <div className="bg-slate-50 px-4 py-5">
              {message ? (
                <div className="max-w-[90%] rounded-2xl rounded-tl-sm bg-white px-3 py-2 text-sm text-slate-800 shadow-sm">
                  {message}
                </div>
              ) : (
                <p className="text-center text-xs text-slate-400">
                  Fill in the purchase form to preview the SMS message.
                </p>
              )}
            </div>
          </div>
          <p className="mt-2 text-center text-xs text-slate-400">
            Preview only — the actual message is generated by the backend template.
          </p>
        </div>
      </div>
    </section>
  )
}
