"""link purchases to products and inventory

Revision ID: 7d2c9a5e1b4f
Revises: 9e1f3c2a4b5d
Create Date: 2026-10-04 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2c9a5e1b4f'
down_revision = '9e1f3c2a4b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchases_product_id'), ['product_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_purchases_product_id_products'), 'products', ['product_id'], ['id'])
        batch_op.create_check_constraint('ck_purchases_quantity_positive', 'quantity IS NULL OR quantity > 0')
        batch_op.create_check_constraint('ck_purchases_unit_price_nonnegative', 'unit_price IS NULL OR unit_price >= 0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint('ck_purchases_unit_price_nonnegative', type_='check')
        batch_op.drop_constraint('ck_purchases_quantity_positive', type_='check')
        batch_op.drop_constraint(batch_op.f('fk_purchases_product_id_products'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchases_product_id'))
        batch_op.drop_column('unit_price')
        batch_op.drop_column('quantity')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
