"""add products and inventory

Revision ID: 9e1f3c2a4b5d
Revises: 114541a315de
Create Date: 2026-10-04 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1f3c2a4b5d'
down_revision = '114541a315de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('minimum_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maximum_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(name) > 0', name='ck_products_name_not_empty'),
    sa.CheckConstraint('maximum_price >= 0', name='ck_products_maximum_price_nonnegative'),
    sa.CheckConstraint('minimum_price >= 0', name='ck_products_minimum_price_nonnegative'),
    sa.CheckConstraint('minimum_price <= maximum_price', name='ck_products_price_range'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_products_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_inventories',
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_shop_inventories_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'shop_id', name='uq_shop_inventories_product_shop')
    )
    with op.batch_alter_table('shop_inventories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_inventories_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_inventories_shop_id'), ['shop_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("movement_type IN ('INITIAL_STOCK', 'MANUAL_ADJUSTMENT', 'SALE')", name='ck_stock_movements_movement_type'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index('ix_stock_movements_product_shop_created', ['product_id', 'shop_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movements_product_shop_created')
        batch_op.drop_index(batch_op.f('ix_stock_movements_shop_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_actor_id'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('shop_inventories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_inventories_shop_id'))
        batch_op.drop_index(batch_op.f('ix_shop_inventories_product_id'))

    op.drop_table('shop_inventories')
    op.drop_table('products')
    # ### end Alembic commands ###
